server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: scanms-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/scanms}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-openapi
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - "Path=/openapi/user"
              filters:
                - "SetPath=/v3/api-docs"
            - id: catalog-service-openapi
              uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
              predicates:
                - "Path=/openapi/catalog"
              filters:
                - "SetPath=/v3/api-docs"
            - id: order-service-openapi
              uri: ${ORDER_SERVICE_URL:http://localhost:8083}
              predicates:
                - "Path=/openapi/order"
              filters:
                - "SetPath=/v3/api-docs"
            - id: payment-service-openapi
              uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
              predicates:
                - "Path=/openapi/payment"
              filters:
                - "SetPath=/v3/api-docs"
            - id: promotion-service-openapi
              uri: ${PROMOTION_SERVICE_URL:http://localhost:8085}
              predicates:
                - "Path=/openapi/promotion"
              filters:
                - "SetPath=/v3/api-docs"
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - "Path=/api/v1/users/**"
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
              predicates:
                - "Path=/api/v1/stores/**,/api/v1/products/**,/api/v1/livestreams/**"
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8083}
              predicates:
                - "Path=/api/v1/orders/**,/api/v1/seller-orders/**,/api/v1/returns/**"
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
              predicates:
                - "Path=/api/v1/payments/**,/api/v1/bank-accounts/**,/api/v1/settlements/**"
            - id: promotion-service
              uri: ${PROMOTION_SERVICE_URL:http://localhost:8085}
              predicates:
                - "Path=/api/v1/vouchers/**,/api/v1/collaborators/**,/api/v1/referrals/**,/api/v1/commissions/**"
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls-primary-name: User Service
    urls:
      - name: User Service
        url: /openapi/user
      - name: Catalog Service
        url: /openapi/catalog
      - name: Order Service
        url: /openapi/order
      - name: Payment Service
        url: /openapi/payment
      - name: Promotion Affiliate Service
        url: /openapi/promotion
